# Generated by Django 6.0.2 on 2026-02-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_city_order_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Thamarassery'),
        ),
    ]
