# Generated by Django 6.0.2 on 2026-02-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
